### ISSUE TITLE
UV Map & Material Import

### ISSUE THREAD

**Issue by DoctorJew** [bjornmp/Men-of-War-Blender-Importer#1]
While models do import with materials applied to them, often times the UVs of the model are not assigned to any texture, as it seems texture themselves are not even setup when importing a model with the script. The UVs are intact it appears, however if I want to export the model to anything useful I have to first manually determine which UV goes to what material.

**Comment by bjornmp** [comment]
I'm not an expert in Blender, so I'm still trying to understand what your issue really is. Is it the texture that's not being loaded? As for now, the script only looks for the textures inside the folder where the model is stored.

**Comment by MCiLuZiioNz** [comment]
Here is an example of what I am talking about: https://i.imgur.com/Yzdq9kp.png

and here is an example where this becomes an issue: https://i.imgur.com/dEVYuAG.png

**Comment by bjornmp** [comment]
Can you tell me which model it is you are loading in the example?

**Comment by MCiLuZiioNz** [comment]
They are for MOW:AS2

**Comment by bjornmp** [comment]
And what's the name of the model/asset so I can take a look? Is this even from the original MOW:AS2 or is it part of a mod?

**Comment by MCiLuZiioNz** [comment]
It's part of a mod, I can pack up the models in a zip if you want.

**Comment by bjornmp** [comment]
Is it available on Steam Workshop?

**Comment by MCiLuZiioNz** [comment]
No, it is not. Was from ModDB. Here is a zip of the models http://puu.sh/qBdoN/c39c1bbe98.zip

**Comment by bjornmp** [comment]
Well, that's an interesting example there. It uses multiple textures inside the same .PLY model. Most standard MOW models aren't built that way and that's why I didn't pay too much attention to it. The script isn't prepared to handle this kind of situation yet.

The script would have to:
- Create vertex groups
- Create a material for each texture
- Assign the correct material to the corresponding vertex group

I also see that the material is composed of separate Diffuse, Normal and Specular textures, which is another important factor. The script currently only loads Diffuse textures.

I will be busy this week so maybe I'm going to take a look into this next weekend.

**Comment by MCiLuZiioNz** [comment]
Well thanks for taking the time to look into it :+1:

**Comment by GSamu** [comment]
Hi Bjor.

Great work!!!

Now, I need to find the way to modify the existing animation for the infantry. Are you planing make some code for this?

I was tried to understand the .anm file but is dificult to me.

Regards.

**Comment by bjornmp** [comment]
This issue has been fixed with a patch a while ago. Just closing this issue.
