### ISSUE TITLE
Update to 2.93

### ISSUE THREAD

**Issue by dhkatz** [bjornmp/Men-of-War-Blender-Importer#3]
Hello, is there any chance this gets update to the latest LTS version of Blender?

Thank you!

**Comment by bjornmp** [comment]
Hi, I'm not really planning to, sorry.

I haven't done anything related to Blender lately and 2.8 also massively broke compatibility (check out the release notes below), so it's more like a new addon rather than an update.

This addon can still be used as a reference in how to parse MoW files though, for anyone interested in creating an addon for 2.8+.

https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API

**Comment by dhkatz** [comment]
Alright. I guess I'll give it shot. Thank you!
